name: jvmhs
version: '0.0.1'
author: Christian Gram Kalhauge
maintainer: Christian Gram Kalhauge <kalhauge@cs.ucla.edu>
synopsis: A library for reading Java class-files

license: MIT
license-file: LICENSE
category: Language, Java, JVM
github: ucla-pls/jvmhs

description: |
  A library to sematically read a class from a file.

ghc-options: -Wall

extra-source-files:
  - LICENSE
  - package.yaml
  - README.md

library:
  dependencies:
    - base >= 4.10 && < 4.11
    - jvm-binary >= 0.1.0 && < 0.2.0
    - lens
    - lens-action
    - zip-archive
    - bytestring
    - directory
    - filepath
    - process
    - containers
    - text
    - mtl
    - fgl
    - fgl-visualize
  source-dirs: src
